/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mon;

import mon.projet.Welcome;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class WelcomeTest {

    @Test
    void ShouldReturnMessage() {
        Welcome welcome = new Welcome();
        String message = welcome.getMessage();

        assertNotNull(message);
    }

    @Test
    void DayMondayBonjour() {
        LocalDateTime date = LocalDateTime.of(2024, 3, 25, 10, 0);
        Welcome welcome = new Welcome();

        String result = welcome.getMessage(date);

        assertEquals("Bonjour", result);
    }
    @Test
    void DayMonday_8h(){
        LocalDateTime date = LocalDateTime.of(2024, 3, 25, 8, 0);
        Welcome welcome = new Welcome();

        String result = welcome.getMessage(date);

        assertEquals("Bon week-end", result);
    }
    @Test
    void DayMonday_9h(){
        LocalDateTime date = LocalDateTime.of(2024, 3, 25, 9, 0);
        Welcome welcome = new Welcome();

        String result = welcome.getMessage(date);

        assertEquals("Bonjour", result);
    }

    @Test
    void DayTuesdayBonApresMidi() {
        LocalDateTime date = LocalDateTime.of(2024, 3, 26, 14, 0);
        Welcome welcome = new Welcome();

        String result = welcome.getMessage(date);

        assertEquals("Bon après-midi", result);
    }

    @Test
    void DayMondayBonsoir() {
        LocalDateTime date = LocalDateTime.of(2024, 3, 25, 20, 0);
        Welcome welcome = new Welcome();

        String result = welcome.getMessage(date);

        assertEquals("Bonsoir", result);
    }

    @Test
    void HappyWeekEnd() {
        LocalDateTime date = LocalDateTime.of(2024, 3, 30, 18, 0);
        Welcome welcome = new Welcome();

        String result = welcome.getMessage(date);

        assertEquals("Bon week-end", result);
    }
    @Test
    void HappyWeekEndSaturday() {
        LocalDateTime date = LocalDateTime.of(2024, 3, 30, 10, 0);
        Welcome welcome = new Welcome();

        String result = welcome.getMessage(date);

        assertEquals("Bon week-end", result);
    }
    @Test
    void HappyWeekEndSunday() {
        LocalDateTime date = LocalDateTime.of(2024, 3, 31, 18, 0);
        Welcome welcome = new Welcome();

        String result = welcome.getMessage(date);

        assertEquals("Bon week-end", result);
    }
}
